# Test your FastAPI endpoints

GET https://lab.eichenbergs.de/
Accept: application/json

###

GET https://lab.eichenbergs.de/ping/sensorId/miflora1
Accept: application/json

###

GET https://lab.eichenbergs.de/restart/sensorId/miflora1
Accept: application/json

###

POST https://lab.eichenbergs.de/Send
Content-Type: application/json

###

POST https://lab.eichenbergs.de/Send
Content-Type: application/json

{
  "esp8266id": "11609734",
  "software_version": "NRZ-2020-133",
  "sensordatavalues": [
    {
      "value_type": "BME280_temperature",
      "value": "8.59"
    },
    {
      "value_type": "BME280_pressure",
      "value": "98516.69"
    },
    {
      "value_type": "BME280_humidity",
      "value": "100.00"
    },
    {
      "value_type": "samples",
      "value": "341784"
    },
    {
      "value_type": "min_micro",
      "value": "28"
    },
    {
      "value_type": "max_micro",
      "value": "1396"
    },
    {
      "value_type": "interval",
      "value": "10000"
    },
    {
      "value_type": "signal",
      "value": "-83"
    }
  ]
}


###

POST https://lab.eichenbergs.de/post_stat
Content-Type: application/json

{
  "esp8266id": "11609734",
  "software_version": "NRZ-2020-133",
  "type": "ping"
}

###

POST https://lab.eichenbergs.de/post_stat
Content-Type: application/json

{
  "esp8266id": "11609734",
  "software_version": "NRZ-2020-133",
  "type": "restart"
}