# Test your FastAPI endpoints

### Main Website
GET https://www.eichenbergs.com/
Accept: application/json

### Get OW
GET http://localhost:8986/get_openweather?lat=51.2005&long=9.9080
Accept: application/json

### Sensor Ping
GET https://www.eichenbergs.com/ping/id/test_sensor
Accept: application/json

### Sensor has restarted
GET https://www.eichenbergs.com/restart/id/test_sensor
Accept: application/json

### Fail Post Send
POST https://www.eichenbergs.com/Send
Content-Type: application/json

### Succeed Post Send
#POST https://www.eichenbergs.com/Send
POST http://localhost:8000/Send
Content-Type: application/json

{
  "id": "test_sensor",
  "software_version": "NRZ-2020-133",
  "sensordatavalues": [
    {
      "value_type": "BME280_temperature",
      "value": "8.59"
    },
    {
      "value_type": "BME280_pressure",
      "value": "98516.69"
    },
    {
      "value_type": "BME280_humidity",
      "value": "100.00"
    },
    {
      "value_type": "samples",
      "value": "341784"
    },
    {
      "value_type": "min_micro",
      "value": "28"
    },
    {
      "value_type": "max_micro",
      "value": "1396"
    },
    {
      "value_type": "interval",
      "value": "10000"
    },
    {
      "value_type": "signal",
      "value": "-83"
    },
    {
      "value_type": "MHZ19B_co2",
      "value": 1188
    }
  ]
}


###

POST https://www.eichenbergs.com/post_stat
Content-Type: application/json

{
  "id": "test_sensor",
  "software_version": "NRZ-2020-133",
  "type": "ping"
}

###

POST https://www.eichenbergs.com/post_stat
Content-Type: application/json

{
  "id": "test_sensor",
  "software_version": "NRZ-2020-133",
  "type": "restart"
}

###

POST https://www.eichenbergs.com/Send
Content-Type: application/json

{
  "id": "test_sensor",
  "sensordatavalues": [
    {
      "value_type": "water_height_percent",
      "value": 0.123
    },
    {
      "value_type": "water_height_volume",
      "value": 321.69
    },
    {
      "value_type": "water_height_height",
      "value": 1.65
    },
    {
      "value_type": "water_height_voltage",
      "value": 1.345
    },
    {
      "value_type": "water_height_location",
      "value": "test location"
    }
  ]
}
###
GET https://www.eichenbergs.com/get_latest
Accept: application/json


###
GET https://www.eichenbergs.com/get_latest
Accept: application/json

###
GET http://localhost:8000/get_openweather?lat=41.893&long=12.483